### ISSUE TITLE
Upsert commented ?

### ISSUE THREAD

**Issue by sabativi** [cinn-labs/meteor-multitenancy#3]
Hello,

Is there any reason whu upsert hook has been disable ?
https://github.com/cinn-labs/meteor-multitenancy/blob/master/tenancy.server.js#L37

**Comment by ccstorch** [comment]
I don't remember the exact reason, I should've put a more described comment in there.

As far as I remember the upsertHook was being called on the insert and update calls, and not only in the upsert calls. But I can't say for sure if that was really the problem.

**Comment by sabativi** [comment]
This makes sense, thanks
